[env]
SECRETS_DIR = "{{config_root}}/../secrets"
TALSECRET_PATH = "{{env.SECRETS_DIR}}/talos/talsecret.sops.yaml"

[tools]
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:siderolabs/talos" = "1.11.5"
"aqua:budimanjojo/talhelper" = "3.0.41"
"aqua:getsops/sops" = "3.11.0"
"aqua:FiloSottile/age" = "1.2.1"
"aqua:go-task/task" = "3.45.5"
"aqua:helm/helm" = "3.19.2"
"aqua:helmfile/helmfile" = "1.2.2"
"aqua:jqlang/jq" = "1.8.1"
"aqua:kubernetes-sigs/kustomize" = "5.7.1"
"aqua:kubernetes/kubectl" = "1.34.0"
"aqua:mikefarah/yq" = "4.49.2"