apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "dns-pool"
spec:
  blocks:
  - cidr: "192.168.104.1/32"
  serviceSelector:
    matchLabels:
      serviceType: dns
---
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "service-pool"
spec:
  blocks:
  - cidr: "192.168.105.1/24"