---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "dns-pool"
spec:
  blocks:
  - cidr: "192.168.104.1/32"
  serviceSelector:
    matchLabels:
      cluster.home.arpa/service-type: dns
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "dns-admin-pool"
spec:
  blocks:
  - cidr: "192.168.104.2/32"
  serviceSelector:
    matchLabels:
      cluster.home.arpa/service-type: dns-admin
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "service-pool"
spec:
  blocks:
  - cidr: "192.168.105.1/24"
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliuml2announcementpolicy_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: service-pool-l2-policy
  namespace: kube-system
spec:
  loadBalancerIPs: true
  interfaces:
  - ^eth.*   # Match all eth interfaces, or specify yours like "eth0"
  nodeSelector:
    matchExpressions: 
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
